spring.application.name=ProyectoProgramacion

spring.datasource.url=jdbc:mariadb://localhost:3306/gestion_uq
spring.datasource.username=uq_app
spring.datasource.password=uq_app_2026
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# JWT
# =========================
jwt.secret=MiClaveSuperSeguraProyectoGestionUQ2026JWT123456789
jwt.expiration-ms=8640000000