spring.application.name=ProyectoGestionUQ

spring.datasource.url=jdbc:mariadb://localhost:3306/gestion_solicitudes
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

server.port=8080

app.jwt.secret=MiClaveSuperSecretaMiClaveSuperSecreta123456789
app.jwt.expiration-ms=86400000

# Google Gemini AI
gemini.api-key=${GEMINI_API_KEY:}
gemini.base-url=https://generativelanguage.googleapis.com
gemini.model=gemini-2.5-flash
gemini.max-tokens=1024
gemini.timeout-ms=10000
gemini.temperature=0.7